### ISSUE TITLE
Planejamento Test Drive com Openshift 4.5 + Quarkus

### ISSUE THREAD

**Issue by luszczynski** [luszczynski/test-drive-openshift#12]
Premissas de todos os labs:
1. Dar a opção de utilizar a web console ou a CLI (oc, kubectl, odo) para executar cada lab

Pre-req

- [x] #36 Instalação do Operator de Serverless
- [x] #36 Instalação do Operator de Tekton
- [x] #36 Instalação do Logging 
- [ ] #37 Criar Playbook de instalação dos componentes de pre-req

Labs principais

- [ ] #13 - Overview do que será executado nos labs
- [ ] #14 - Acesso ao ambiente (Etherpad, Terminal na web, Terminal no laptop - opcional, Web Console)
- [ ] #15 - Deploy de uma aplicação (backend) usando s2i (Quarkus) + Mostrando Web Console
- [ ] #16 - Deploy de uma aplicação usando helm (frontend)
- [ ] #17 - Tolerancia a Falha
- [ ] #18 - Integração continua com Webhook
- [ ] #19 - Health Check (Liveness, Readiness e Start Probe)
- [ ] #20 - Banco de Dados com Docker Hub ou Quay com PV
- [ ] #21 - Limite de Recurso (Limits e Request)
- [ ] #22 - Auto Scale 
- [ ] #23 - Pipeline com Jenkins (simples)
- [ ] #24 - Pipeline com Tekton (simples)
- [ ] #25 - Network Policy
- [ ] #26 - Logging agregado
- [ ] #27 - Rollback
- [ ] #28 - ConfigMap e Secrets
- [ ] #38 - Idle

Labs Bonus

- [ ] #29 - Lab Bonus (Auto Scale e Idle com Knative)
- [ ] #30 - Lab Bonus (Kafka)
- [ ] #31 - Lab Bonus (Prometheus e Grafana)
- [ ] #32 - Lab Bonus (Deploy de uma aplicação usando template)
- [ ] #33 - Lab Bonus (Deploy usando binary deployment)
- [ ] #34 - Lab Bonus (Deploy usando Dockerfile)
- [ ] #35 - Lab Bonus Ansible
